train_dataset_path: "/home/ubuntu/comp_astro_24/Assigments/Assigments 2/Data/kepler/data_injected/exoTrain.csv"
test_dataset_path: "/home/ubuntu/comp_astro_24/Assigments/Assigments 2/Data/kepler/data_injected/exoTest.csv"
type_of_kernel: "rbf"
batch_size: 32
epochs: 20
data_path: "/home/ubuntu/comp_astro_24/Assigments/Assigments 2/Data/img_data/img.npy"
label_path: "/home/ubuntu/comp_astro_24/Assigments/Assigments 2/Data/img_data/img_label.npy"
Training: False